### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by marijnvanwezel** [neo4j-php/php-cypher-dsl#52]
The current documentation is very out of date. It should be updated to document the latest features. Also, some breaking changes causes the examples to no longer work correctly.

**Comment by marijnvanwezel** [comment]
I have updated almost all documentation. The only things that still need to be done are:

* Add examples to `WITH` clause documentation;
* Add examples to `WHERE` clause documentation.

**Comment by beshoo** [comment]
> I have updated almost all documentation. The only things that still need to be done are:
> 
> * Add examples to `WITH` clause documentation;
> * Add examples to `WHERE` clause documentation.

I am testing the where example 

```

require_once './vendor/autoload.php'; // Use require_once to include the autoload file

use function WikibaseSolutions\CypherDSL\node;
use function WikibaseSolutions\CypherDSL\query;

$n = node('Person');
$query = query()
    ->match($n)
    ->where($n->property('name')->equals('Peter'))
    ->returning($n)
    ->build();

print $query;
```

I have this error:
`Fatal error: Class WikibaseSolutions\CypherDSL\Expressions\Operators\Equality contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (WikibaseSolutions\CypherDSL\Patterns\Pattern::hasVariableSet, WikibaseSolutions\CypherDSL\Patterns\Pattern::withVariable, WikibaseSolutions\CypherDSL\Patterns\Pattern::getVariable) in D:\xampp\htdocs\neo4j\vendor\wikibase-solutions\php-cypher-dsl\src\Expressions\Operators\Equality.php on line 17`

**Comment by beshoo** [comment]
![image](https://github.com/neo4j-php/php-cypher-dsl/assets/4635115/5114c8b5-2240-4df0-bd66-9686c9200a9c)

**Comment by beshoo** [comment]
Is there any update on this matter? It's already 2024!

**Comment by marijnvanwezel** [comment]
> Is there any update on this matter? It's already 2024!

This issue is already closed. If you notice something wrong/out-of-date in the documentation, please open a new issue for it. Thanks!
